### ISSUE TITLE
question: "classTransformer.plainToClass is not a function" when using simple validator in class (nestjs ValidationPipe)

### ISSUE THREAD

**Issue by tiagosiebler** [typestack/class-validator#1411]
**I was trying to...**
Apply simple validations on a data transfer object (simple class) used in nestjs:

```typescript
import { ExchangeName, TransactionSide } from "../exchange.model";
import { IsNotEmpty, IsNumber, IsString } from 'class-validator';

export class CreateTransactionDto {
  @IsNotEmpty()
  @IsString()
  coin: string;

  @IsNotEmpty()
  @IsNumber()
  price: number;

  @IsNotEmpty()
  @IsNumber()
  qty: number;

  @IsNotEmpty()
  @IsNumber()
  size: number;

  @IsNotEmpty()
  @IsString()
  side: TransactionSide;

  @IsNotEmpty()
  @IsNumber()
  time: number;//timestamp

  @IsNotEmpty()
  @IsString()
  exchange: ExchangeName;
}
```

Simple POST handler:
```typescript
  @Post()
  async newTransaction(@Body() createTranactionDto: CreateTransactionDto) {
    return await this.transactionService.newTransaction(createTranactionDto);
  }
```

Invoked useGlobalPipes:
```typescript
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe());

  await app.listen(ServerPort);
}
bootstrap();
```

**The problem:**
Any request triggers a class transformer error...
```
[Nest] 84636  - 11/20/2021, 9:18:43 PM   ERROR [ExceptionsHandler] classTransformer.plainToClass is not a function
TypeError: classTransformer.plainToClass is not a function
    at ValidationPipe.transform (/projectroot/node_modules/@nestjs/common/pipes/validation.pipe.js:51:39)
    at /projectroot/node_modules/@nestjs/core/pipes/pipes-consumer.js:16:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by tiagosiebler** [comment]
So it looks like it's the latest version of class-transformer:
```
    "class-transformer": "^0.5.0",
```

downgrade to 0.4.0 (`npm i class-transformer@0.4.0`) and the problem solves itself...

**Comment by tiagosiebler** [comment]
Same issue as reported here: https://github.com/nestjs/nest/issues/8637

**Comment by c43721** [comment]
I opened a discussion on this in the class-transformer github repo.

You can view it here: https://github.com/typestack/class-transformer/issues/995

**Comment by dammy001** [comment]
same issue. had to downgrade to 0.4.0

**Comment by dammy001** [comment]
same issue. had to downgrade to 0.4.0

**Comment by codeyourwayup** [comment]
npm i class-transformer@0.4.0 works, class-transformer: ^0.4.0 this not working.

**Comment by codeyourwayup** [comment]
yarn add class-transformer@0.4.0

**Comment by NoNameProvided** [comment]
Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
