### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by idchlife** [typestack/class-validator#146]
Error appears here: https://github.com/typestack/class-validator/blob/master/src/metadata/MetadataStorage.ts#L79

Everything is quiet ordinar. I have this class for validation:

```typescript
export class RegisterMasterBody {
  @IsEmail()
  email: string;

  @MinLength(6)
  password: string;

  name: string;

  instagram?: string;

  description?: string;

  lat?: number;

  long?: number;
}
```

And here how I check for errors:

```typescript
@Post()
  @Render("register")
  public async register(@Res() res: Response, @Body() body: RegisterMasterBody) {
    try {
      console.log(body, typeof body, body.constructor);
      const errors = await validate(body, { skipMissingProperties: true });
      console.log(errors, "errors of validate");
    } catch (error) {
      console.error(error, "POST REGISTER");
    }
  }
```

in console.log typeof body - "object", constructor undefined

But inside here Error appears here: https://github.com/typestack/class-validator/blob/master/src/metadata/MetadataStorage.ts#L79 metadata.target is RegisterMasterBody

I tried to gather as much info as I can, since this is another project full of everything to strip it down and create repo with isolated reproduction :(

Class validator is the same version as in this repo.

edit: worth mention - there are more properties that do not belong to RegisterMasterBody coming in request. But I tried adding them to RegisterMastBody - did not help

**Comment by NoNameProvided** [comment]
Please provide us some example data, what we use in your example to reproduce your issue. Thanks!

**Comment by NoNameProvided** [comment]
Closing as no response from the poster. Probably this is fixed anyway with the latest changes.

**Comment by theobouwman** [comment]
```
[Nest] 77719   - 2018-5-13 22:27:55   [ExceptionsHandler] Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
    at /Users/theobouwman/dev/projects/webshop_top/src/metadata/MetadataStorage.ts:79:37
    at Array.filter (<anonymous>)
    at MetadataStorage.getTargetValidationMetadatas (/Users/theobouwman/dev/projects/webshop_top/src/metadata/MetadataStorage.ts:75:61)
    at ValidationExecutor.execute (/Users/theobouwman/dev/projects/webshop_top/src/validation/ValidationExecutor.ts:44:54)
    at Validator.coreValidate (/Users/theobouwman/dev/projects/webshop_top/src/validation/Validator.ts:31:18)
    at Validator.validate (/Users/theobouwman/dev/projects/webshop_top/src/validation/Validator.ts:56:21)
    at Object.validate (/Users/theobouwman/dev/projects/webshop_top/src/index.ts:49:44)
    at ResellerBrandArticleController.newArticlePost (/Users/theobouwman/dev/projects/webshop_top/src/controllers/reseller.brand.article.controller.ts:28:5)
    at RouterExecutionContext.<anonymous> (/Users/theobouwman/dev/projects/webshop_top/node_modules/@nestjs/core/router/router-execution-context.js:52:33)
    at Generator.next (<anonymous>)
```
Same error here.

This is my code:
```
import {IsNumber, MaxLength, MinLength} from 'class-validator';

export class NewArticleDto {
  @MinLength(3)
  readonly name: string;

  @MinLength(10)
  @MaxLength(500)
  readonly description: string;

  @IsNumber()
  readonly price: number;

  @IsNumber()
  readonly stock: number;
}
```

**Comment by theobouwman** [comment]
@NoNameProvided could you help?

**Comment by kalinichenko88** [comment]
@NoNameProvided I have this problem too

```typescript
import {
	ValidationSchema,
	ValidationTypes,
	validateSync,
	registerSchema
} from "class-validator";

export const UserUpdateSchema: ValidationSchema = {
	name: "UserUpdateSchema",
	properties: {
		name: [
			{
				type: ValidationTypes.IS_DEFINED,
			}
		]
	}
};

export class UserUpdateArgsValidator {
	constructor() {
		registerSchema(UserUpdateSchema);
	}

	validate({ data }) {
		console.log(data);
		const errors = validateSync("UserCreateSchema", data);
		////
	}
}
```

In console.log

```
{ name: 'Ivan', role: 'admin' }
```

And error

```
TypeError: Cannot read property 'prototype' of undefined
    at <path>/node_modules/class-validator/metadata/MetadataStorage.js:69:37
```

**Comment by NoNameProvided** [comment]
Hi @kalinichenko88! 

Thanks for the example! I have trouble reproducing the error. Can you try with the latest version of class-validator? 

My test code on [stackblitz](https://stackblitz.com/edit/class-validator-146):

```ts
import {
	ValidationSchema,
	ValidationTypes,
	validateSync,
	registerSchema
} from "class-validator";

export const UserUpdateSchema: ValidationSchema = {
	name: "UserUpdateSchema",
	properties: {
		name: [
			{
				type: ValidationTypes.IS_DEFINED,
			}
		]
	}
};

export const data = { name: 'Ivan', role: 'admin' };

registerSchema(UserUpdateSchema);
const errors = validateSync("UserUpdateSchema", data);
console.log(errors);
```

**Comment by vlapo** [comment]
Closing this out due to inactivity. Please file a new issue if you are encountering a similar or related problem.
