### ISSUE TITLE
fix: `@IsPort()` validation fails when providing a number value

### ISSUE THREAD

**Issue by GO-DIE** [typestack/class-validator#1543]
### Description

**Minimal code-snippet showcasing the problem**
 

```ts
import 'reflect-metadata';
import { plainToClass } from 'class-transformer';
import {
  IsFQDN,
  IsNotEmpty,
  IsNumber,
  IsPort,
  IsString,
  validateSync,
  ValidateNested,
} from 'class-validator';

class Http {
  @IsNotEmpty()
  @IsNumber()
  port: number;
}

class Redis {
  @IsNotEmpty()
  @IsFQDN()
  host: string;

  @IsNotEmpty()
  @IsPort()
  port: number;

  @IsNotEmpty()
  @IsString()
  password: string;
}

class DB {
  @ValidateNested()
  @IsNotEmpty()
  redis: Redis;
}

class EnvironmentVariables {
  @ValidateNested()
  @IsNotEmpty()
  http: Http;

  @ValidateNested()
  @IsNotEmpty()
  DB: DB;
}

function validate(config: Record<string, unknown>) {
  const validatedConfig = plainToClass(EnvironmentVariables, config, {
    enableImplicitConversion: true,
  });
  const errors = validateSync(validatedConfig, {
    skipMissingProperties: false,
  });

  if (errors.length > 0) {
    throw new Error(errors.toString());
  }
  return validatedConfig;
}

const config = {
  http: { port: 3000 },
  DB: {
    redis: { host: 'redis.com', port: 6379, password: 'password' },
  },
};
validate(config);

```

### Expected behavior

Validation passes
### Actual behavior

Validation error
```
Error: An instance of EnvironmentVariables has failed the validation:
 - property DB.redis.port has failed the following constraints: isPort 

    at validate (c:\Users\Administrator\Desktop\mine-repos\nestjs\1.ts:58:11)
    at Object.<anonymous> (c:\Users\Administrator\Desktop\mine-repos\nestjs\1.ts:69:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module.m._compile (D:\Nodejs\Nodejsnode_global\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Nodejs\Nodejsnode_global\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at main (D:\Nodejs\Nodejsnode_global\node_modules\ts-node\src\bin.ts:198:14)
```

**Comment by xujif** [comment]
***@***.***浊酒

**Comment by NoNameProvided** [comment]
The port validator expects a string value. If you want to accept only numbers as port then you can use:

```ts
class MyPayload {
  @IsNumber()
  @Min(0)
  @Max(65535)
  port: number;
}
```

For more details, see: https://github.com/typestack/class-validator/issues/826#issuecomment-1321153083
