### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'constructor')

### ISSUE THREAD

**Issue by SangVoM** [typestack/class-validator#1815]
### Description
When trying to use the `validate` method to validate with DTO in a custom validator, I'm getting this error:
```
TypeError: Cannot read properties of undefined (reading 'constructor')
    at ValidationExecutor.execute (/Users/sangvo/Documents/GitHub/boilerplate-microservice-nestjs/app-service/node_modules/src/validation/ValidationExecutor.ts:57:14)
    at Validator.coreValidate (/Users/sangvo/Documents/GitHub/boilerplate-microservice-nestjs/app-service/node_modules/src/validation/Validator.ts:107:14)
    at Validator.validate (/Users/sangvo/Documents/GitHub/boilerplate-microservice-nestjs/app-service/node_modules/src/validation/Validator.ts:32:17)
    at validate (/Users/sangvo/Documents/GitHub/boilerplate-microservice-nestjs/app-service/node_modules/src/index.ts:52:40)
    at RPCValidationPipe.transform (/Users/sangvo/Documents/GitHub/boilerplate-microservice-nestjs/app-service/src/common/pipe/rpc-validation.pipe.ts:15:34)
    at /Users/sangvo/Documents/GitHub/boilerplate-microservice-nestjs/app-service/node_modules/@nestjs/core/pipes/pipes-consumer.js:16:33
```

My code:
```ts
import { ArgumentMetadata, Injectable, PipeTransform } from '@nestjs/common';
import { validate } from 'class-validator';
import { plainToInstance } from 'class-transformer';
import { RpcException } from '@nestjs/microservices';
import * as moment from 'moment';

@Injectable()
export class RPCValidationPipe implements PipeTransform<any> {
  async transform(value: any, { metatype }: ArgumentMetadata) {
    if (!metatype || !RPCValidationPipe.toValidate(metatype)) {
      return value;
    }
    const object = plainToInstance(metatype, value);
    const errors = await validate(object);

    if (errors.length > 0) {
      throw new RpcException(
        JSON.stringify(RPCValidationPipe.flattenValidationErrors(errors)),
      );
    }
    return value;
  }

  private static toValidate(metatype: any): boolean {
    const types: any[] = [String, Boolean, Number, Array, Object];
    return !types.includes(metatype);
  }

  private static flattenValidationErrors(validationErrors) {
    const errorMsg = {};
    validationErrors.map((ve) => {
      errorMsg[ve.property] = [...Object.values(ve.constraints)];
    });
    return errorMsg;
  }
}
```

The error is from this line. `const errors = await validate(object);`

```ts
  @IsEmailExist({ message: 'email is exist' })
  @IsEmail()
  @IsNotEmpty()
  email: string;
```
I tried other issues but it still crashes from [643](https://github.com/typestack/class-validator/issues/643)

**Comment by braaar** [comment]
Thanks for the issue. Could you provide a runnable reproduction of this issue, such as a stackblitz, codepen or code sandbox?

**Comment by SangVoM** [comment]
> Thanks for the issue. Could you provide a runnable reproduction of this issue, such as a stackblitz, codepen or code sandbox?

I tried it on codesandbox but it doesn't work on the server there. On demo https://codesandbox.io/s/demo-nestjs-forked-tkhv25?file=/src/validation.pipe.ts

**Comment by NoNameProvided** [comment]
Sorry, without a reproducible example we cannot help you. 

My guess would be that the `object` variable holds something different than you expect. When logging that before validation you should see a class instance logged with the `email` field on it.
