### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by kikar** [typestack/class-validator#236]
I'm getting a very strange error on validation, triggered by a specific stringEnum field called `type`:
```typescript
class Feature {
  @IsOptional({ groups: ['all'] })
  @IsEnum(FeatureTypes, { groups: ['all'] })
  // TypeORM decorator - @Column({ type: 'enum', enum: FeatureTypes })
  type: FeatureTypes;
}
```
The enum is defined like this:
```typescript
export enum FeatureTypes {
  Alpha = 'alpha',
  Beta = 'beta',
  Standard = 'standard'
}
```
And the error is the following:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Validator.isEnum (node_modules/validation/Validator.ts:354:35)
    at Validator.validateValueByMetadata (node_modules/validation/Validator.ts:141:29)
    at node_modules/validation/ValidationExecutor.ts:196:44
    at Array.filter (<anonymous>)
    at ValidationExecutor.defaultValidations (node_modules/validation/ValidationExecutor.ts:189:14)
    at node_modules/validation/ValidationExecutor.ts:94:18
    at Array.forEach (<anonymous>)
    at ValidationExecutor.execute (node_modules/validation/ValidationExecutor.ts:70:39)
    at Validator.coreValidate (node_modules/validation/Validator.ts:31:18)
    at Validator.validate (node_modules/validation/Validator.ts:56:21)
    at Object.validate (node_modules/index.ts:49:44)
```

Any idea what it could be?
```
Version: 0.8.5
OS: Mac
Node: 8.11.1
```

**Comment by NoNameProvided** [comment]
Hi @kikar! 

This issue is caused because in your

```ts
@IsEnum(FeatureTypes, { groups: ['all'] })
``` 

line the `FeatureTypes` enum is undefined. Please double check your code. (`console.log` before your class declaration.)

I will go ahead and close this ticket, please let me know if the issue still persist.

**Comment by kikar** [comment]
Thanks a lot! Must be a weird Typescript bug that failed to import the Enum correctly.
