### ISSUE TITLE
class-tranformer + class-validator -> problem with nested object validation

### ISSUE THREAD

**Issue by bkotrys** [typestack/class-validator#306]
**Related to:** https://github.com/typestack/class-transformer/issues/226

I use `class-transformer` with `class-validator` to validate request body. I would like to validate class with nested object - **I need to check whether the given object is correct but don't allow to provide an array of objects** 

### How my implementation looks like:
```js
// Class definition with validation rules
class A {
  @IsDefined()
  @IsString()
  public x: string;
  // ... other properties
}

class B {
  @IsDefined()
  @IsString()
  public type!: string;

  @IsDefined()
  @ValidateNested()
  @Type(() => A)
  public nested!: A;
}
```

```js
// invalid request object with array (B[]) instead of object (B)
var requestObjB = {
   type: "test type"
   nested: [{ x: "test x" }] 
}
```

```js
// try to validate request object
validate(plainToClass(B, requestObjB))
```

**Validation failed and I get this error:**
```
 TypeError: newValue_1.push is not a function
    at /Users/bartosz/dev/user-data-api/src/TransformOperationExecutor.ts:67:34
    at Array.forEach (<anonymous>)
    at TransformOperationExecutor.transform (/Users/bartosz/dev/user-data-api/src/TransformOperationExecutor.ts:41:30)
    at _loop_1 (/Users/bartosz/dev/user-data-api/src/TransformOperationExecutor.ts:226:43)
    at TransformOperationExecutor.transform (/Users/bartosz/dev/user-data-api/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
    at _loop_1 (/Users/bartosz/dev/user-data-api/src/TransformOperationExecutor.ts:226:43)
    at TransformOperationExecutor.transform (/Users/bartosz/dev/user-data-api/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
```

Is it possible to solve this problem or maybe there is better way to handle this kind of validation?

**Comment by 19majkel94** [comment]
`public nested!: A[];` not `!: A;`

**Comment by bkotrys** [comment]
@19majkel94 It doesn't satisfied me because I don't want to give a chance to send list of objects. 

`The rules are`:
👍 object, 
👎 array of objects

When someone send an array of object I would like to respond with validation error **`nested property is in wrong format`**

**Comment by 19majkel94** [comment]
The problem is with `class-transformer` - you declare an object type, you provide an array and it fails on transform.

**Comment by bkotrys** [comment]
yeah, you have right. I was hoping that there is other way to handle this problem than validate request  object format before transforming it with `class-transformer` and then validate it again with `class-validator`

**Comment by bkotrys** [comment]
Any updates here? 

> @19majkel94 So what's the recommended way forward here (since you're familiar with both xformer and validator)?

**Comment by vlapo** [comment]
I think the only way how to achieve this is https://github.com/typestack/class-validator#defining-validation-schema-without-decorators but I am not sure in what state is this feature.

**Comment by michal** [comment]
It's pretty old but... adding IsNotEmptyObject or IsObject will not allow arrays, not perfect because will add different error, considering other solutions this was good enough for me.

```
  @IsDefined()
  @IsNotEmptyObject() / @IsObject()
  @ValidateNested()
  @Type(() => A)
  public nested!: A;
```

**Comment by mikezamoracentauri** [comment]
Thanks, this is exactly what I was looking for.

**Comment by rcupic** [comment]
> It's pretty old but... adding IsNotEmptyObject or IsObject will not allow arrays, not perfect because will add different error, considering other solutions this was good enough for me.
> 
> ```
>   @IsDefined()
>   @IsNotEmptyObject() / @IsObject()
>   @ValidateNested()
>   @Type(() => A)
>   public nested!: A;
> ```

These statements are properly parsing nested object, but I have another issue. If I omit one required field or if I send a string instead of a number, Nest js validation pipe throws an Internal Error.

[UPDATE]
Probably error handling or something is bugged.
I have set everything to be optional in nested object and now I have to validate everything manully.
My nested object class now looks like this:

```
class TastingLocationCreateDto {
  @IsOptional()
  public address?: string;

  @IsOptional()
  public lat?: number;

  @IsOptional()
  public long?: number;
}
```
