### ISSUE TITLE
ValidateNested, unhandled exception when provided array contains null

### ISSUE THREAD

**Issue by golozubov** [typestack/class-validator#312]
Hi!

I'm getting TypeError when validating array of objects that contains nulls among another objects.
Let's consider the next example:

```ts
class MySubClass {
    @MinLength(5)
    name: string;
}

class MyClass {
    @ValidateNested()
    mySubClasses: MySubClass[];
}

const model = new MyClass();
model.mySubClasses = [null, new MySubClass()];
```

Here you can see `null` in `mySubClasses` array. Looks legit, right?

But invocation of `validator.validate(model)` causes the next error (I've succeeded reproducing this in tests):

```
TypeError: Cannot read property 'constructor' of null
    at ValidationExecutor.execute (build/compiled/src/validation/ValidationExecutor.js:43:88)
    at /Users/user/Develop/class-validator/build/compiled/src/validation/ValidationExecutor.js:218:27
    at Array.forEach (<anonymous>)
    at /Users/user/Develop/class-validator/build/compiled/src/validation/ValidationExecutor.js:215:23
    at Array.forEach (<anonymous>)
    at ValidationExecutor.nestedValidations (build/compiled/src/validation/ValidationExecutor.js:209:19)
    at /Users/user/Develop/class-validator/build/compiled/src/validation/ValidationExecutor.js:82:19
    at Array.forEach (<anonymous>)
    at ValidationExecutor.execute (build/compiled/src/validation/ValidationExecutor.js:62:39)
    at Validator.coreValidate (build/compiled/src/validation/Validator.js:63:18)
    at Validator.validate (build/compiled/src/validation/Validator.js:72:21)
    at Context.<anonymous> (build/compiled/test/functional/nested-validation.spec.js:177:26)

```

Desired behavior: don't fail on `null`, just skip it and continue validating the rest elements of array.

**Comment by golozubov** [comment]
Also I'm getting the next error with `whitelist: true`
```
TypeError: Cannot delete property '0' of [object String]
    at /Users/user/Develop/class-validator/build/compiled/src/validation/ValidationExecutor.js:106:89
    at Array.forEach (<anonymous>)
    at ValidationExecutor.whitelist (build/compiled/src/validation/ValidationExecutor.js:106:38)
    at ValidationExecutor.execute (build/compiled/src/validation/ValidationExecutor.js:60:18)
    at /Users/user/Develop/class-validator/build/compiled/src/validation/ValidationExecutor.js:218:27
    at Array.forEach (<anonymous>)
    at /Users/user/Develop/class-validator/build/compiled/src/validation/ValidationExecutor.js:215:23
    at Array.forEach (<anonymous>)
    at ValidationExecutor.nestedValidations (build/compiled/src/validation/ValidationExecutor.js:209:19)
    at /Users/user/Develop/class-validator/build/compiled/src/validation/ValidationExecutor.js:82:19
    at Array.forEach (<anonymous>)
    at ValidationExecutor.execute (build/compiled/src/validation/ValidationExecutor.js:62:39)
    at Validator.coreValidate (build/compiled/src/validation/Validator.js:63:18)
    at Validator.validate (build/compiled/src/validation/Validator.js:72:21)
    at Context.<anonymous> (build/compiled/test/functional/nested-validation.spec.js:178:26)
```
in this test:
```
    class MySubClass {
        @MinLength(5)
        name: string;
    }

    class MyClass {
        @ValidateNested({ each: true })
        mySubClasses: MySubClass[];
    }

    const model = new MyClass();
    model.mySubClasses = <any> ["test", new MySubClass()];
    model.mySubClasses[1].name = "my";

    return validator.validate(model, { whitelist: true })
```
It seems that ValidationExecutor.execute() can't handle primitive types properly.
Maybe I'm using @ValidateNested incorrectly here?

**Comment by mfazer** [comment]
Worth to update [this **example** in source](https://github.com/typestack/class-validator/blob/master/sample/sample3-nested-objects/Post.ts) code after fix.

**Comment by jmtelljohann** [comment]
It looks like there's a PR fixing this issue and it's been tagged as part of the 0.10.1 milestone. Anyone know when that milestone is targeting release?

**Comment by NoNameProvided** [comment]
The provided reproduction returns the expected validation errors. 

```ts
import { MinLength, validate, ValidateNested } from "class-validator";

class MySubClass {
  @MinLength(5)
  name: string;
}

class MyClass {
  @ValidateNested()
  mySubClasses: MySubClass[];
}

const model = new MyClass();
model.mySubClasses = [null, new MySubClass()];

validate(model).then(validationErrors => {
  console.log(validationErrors);
  validationErrors.forEach(error => console.log(error.toString()))
}).catch(console.error)
```

Validation result:
```
An instance of MyClass has failed the validation:
- property mySubClasses[0].mySubClasses has failed the following constraints: nestedValidation
- property mySubClasses[1].name has failed the following constraints: minLength
```

**Comment by tmtron** [comment]
@NoNameProvided and how can we allow `null` values in the array?

This is related to #1382 and the following does not work:
```typescript
  @IsOptional({ each: true })
  @ValidateIf((obj, val) => val !== null, {
    each: true
  })
```
see this [Stackblitz example](https://stackblitz.com/edit/typescript-rccwgh?file=index.ts)
