### ISSUE TITLE
@Max(4) is giving me an error on a 4 char number?

### ISSUE THREAD

**Issue by RyannGalea** [typestack/class-validator#341]
For some reason on Postalcode @Max(4) is giving me an error that it's greater than 4 characters? continually.

I'm trying to ensure that the postalCode is always 4 chars
```

mutation {
  addProperty(
    input: {
      houseNo: "3"
      streetName: "Station"
      streetType: STREET
      suburb: "Douglas Park"
      state: NSW
      postalCode:2569
      location: { coordinates: [-111, 44] }
    }
  ) {
    _id
    houseNo
    streetName
  }
}

```

```
@InputType()
export class PropertyInput  {

  @Field()
  @Length(1, 10)
  houseNo: string

  @Field()
  @Length(2, 255)
  streetName: string
  
  @Field(type => StreetType)
  @Length(1, 255)
  @IsEnum(StreetType)
  streetType: string

  @Field()
  @Length(1, 255)
  suburb: string
  
  @Field(type => State)
  @Length(2, 3)
  @IsEnum(State)
  state: string
  
  @Field(type => Int)
  @IsInt()
  @Max(4)
  postalCode: number

  @Field({nullable: true})
  @Length(2, 255)
  crossStreet: string

  @Field(type => LocationInput)
  @ValidateLocation()
  location: LocationInput

}
```

```
@ObjectType()
export class Property extends Typegoose {

  @Field()
  readonly _id: ObjectID

  @Field()
  @prop({required: true})
  houseNo: string

  @Field()
  @prop({required: true})
  streetName: string
  
  @Field(type => StreetType)
  @prop({required: true, enum: StreetType})
  streetType: string

  @Field()
  @prop({required: true})
  suburb: string
  
  @Field(type => State)
  @prop({required: true, enum: State})
  state: string
  
  @Field(type => Int)
  @prop({required: true}) 
  postalCode: number

  @Field()
  @prop()
  crossStreet: string

  @Field(type => Location)
  @prop()
  location: Location

}
```

```
{
  "errors": [
    {
      "message": "Argument Validation Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addProperty"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "validationErrors": [
            {
              "target": {
                "houseNo": "3",
                "streetName": "Station",
                "streetType": "Street",
                "suburb": "Douglas Park",
                "state": "NSW",
                "postalCode": 2569,
                "location": {
                  "coordinates": [
                    -111,
                    34
                  ]
                }
              },
              "value": 2569,
              "property": "postalCode",
              "children": [],
              "constraints": {
                "max": "postalCode must not be greater than 4"
              }
            }
          ],
          "stacktrace": [
            "Error: Argument Validation Error",
            "    at Object.<anonymous> (C:\\prosperty\\server\\node_modules\\type-graphql\\dist\\resolvers\\validate-arg.js:21:19)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (C:\\prosperty\\server\\node_modules\\tslib\\tslib.js:105:69)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by marianocordoba** [comment]
You are validating that `postalCode` is not greater than 4, not that it doesn't have 4 digits. To check that a number has 4 digits you can do something like:

```
@Min(1000)
@Max(9999)
postalCode: number;
```

**Comment by RyannGalea** [comment]
@marianocordoba  Shouldn't this logic work though? Checks if it less than or equal too? What am I missing here?

@Min(min: number) | Checks if the given number is greater than or equal to given number.
@Max(max: number) | Checks if the given number is less than or equal to given number.

**Comment by fwoelffel** [comment]
I have the feeling that you might be mistaking the number value with the number length. If you want to validate that the postal code is a 4-char number, @marianocordoba's answer would be the way to go.

**Comment by RyannGalea** [comment]
@fwoelffel lol I definitely am :( idiot, knew I was doing something stupid here.
