### ISSUE TITLE
Buffer type not working

### ISSUE THREAD

**Issue by phoenix741** [typestack/class-validator#348]
Hi,

I have a type RegistrationUserInput with the following code : 

```
import { InputType, Field, ID } from 'type-graphql';
import { MinLength, ValidateNested } from 'class-validator';
import { EncryptedBlockInput } from '../../shared/dto/encrypted-block-input.dto';

@InputType({ description: 'Input used to register a new user' })
export class RegistrationUserInput {
  @Field(type => ID, { description: 'Login of the user' })
  @MinLength(4)
  _id: string;

  @Field({ description: 'Password used for registration' })
  @MinLength(8)
  password: string;

  @Field(type => EncryptedBlockInput, { description: 'Encrypted master key' })
  @ValidateNested()
  encryption: EncryptedBlockInput;
}

```

that contains a EncryptedBlockInput with the following content : 

```
import { Field, ObjectType } from 'type-graphql';

@ObjectType({ description: 'Master key encrypted for the user' })
export class EncryptedBlock {
  @Field(type => Buffer, { description: 'Salt added to encrypt the master key' })
  salt: Buffer;

  @Field(type => Buffer, { description: 'Initialization Vector' })
  iv: Buffer;

  @Field(type => Buffer, { description: 'Content encrypted with salt' })
  content: Buffer;

  @Field(type => Buffer, { description: 'Authentification tag' })
  authTag: Buffer;
}
```

With the help of GraphQL and Scalar type, i have a base64 string that is converted to Buffer before the class-validator is launched.

When i try to validate the object, the creation of the Buffer object will failed with the message : 

> The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined

This is not possible to call Buffer like "new Buffer()" but we should create a Buffer with Buffer.from(....). As class-validator don't known Buffer object, class-validator try to create it from empty constructor and fail.

How can I deactivate the validation of the embedded object or add Buffer construction to the class-validator ?

Thanks
Ulrich

The stacktrace :  

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at new Buffer (buffer.js:182:17)
    at TransformOperationExecutor.transform (/home/phoenix/Developpement/Shadoware.Org/Private/Website/passprotect/passprotect-server-2/src/TransformOperationExecutor.ts:119:32)
    at _loop_1 (/home/phoenix/Developpement/Shadoware.Org/Private/Website/passprotect/passprotect-server-2/src/TransformOperationExecutor.ts:226:43)
    at TransformOperationExecutor.transform (/home/phoenix/Developpement/Shadoware.Org/Private/Website/passprotect/passprotect-server-2/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
    at _loop_1 (/home/phoenix/Developpement/Shadoware.Org/Private/Website/passprotect/passprotect-server-2/src/TransformOperationExecutor.ts:226:43)
    at TransformOperationExecutor.transform (/home/phoenix/Developpement/Shadoware.Org/Private/Website/passprotect/passprotect-server-2/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
    at ClassTransformer.plainToClass (/home/phoenix/Developpement/Shadoware.Org/Private/Website/passprotect/passprotect-server-2/src/ClassTransformer.ts:43:25)
    at Object.plainToClass (/home/phoenix/Developpement/Shadoware.Org/Private/Website/passprotect/passprotect-server-2/src/index.ts:37:29)
    at ValidationPipe.transform (/home/phoenix/Developpement/Shadoware.Org/Private/Website/passprotect/passprotect-server-2/node_modules/@nestjs/common/pipes/validation.pipe.js:50:41)
    at transforms.reduce (/home/phoenix/Developpement/Shadoware.Org/Private/Website/passprotect/passprotect-server-2/node_modules/@nestjs/core/pipes/pipes-consumer.js:15:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by vlapo** [comment]
I see your issue in `class-transformer` (https://github.com/typestack/class-transformer/issues/249). Did you resolved your problem?

**Comment by phoenix741** [comment]
Yes, thanks
