### ISSUE TITLE
Bug: var phoneUtil = undefined();

### ISSUE THREAD

**Issue by AndrewCathcart** [typestack/class-validator#569]
For; "class-validator": "^0.12.0-rc.0",

C:\Users\newca\Desktop\projects\nestjs\nestjs-todo\node_modules\class-validator\bundles\index.umd.js:11298
    var phoneUtil = undefined();
                    ^

TypeError: undefined is not a function
    at C:\Users\newca\Desktop\projects\nestjs\nestjs-todo\node_modules\class-validator\bundles\index.umd.js:11298:21
    at C:\Users\newca\Desktop\projects\nestjs\nestjs-todo\node_modules\class-validator\bundles\index.umd.js:2:68
    at Object.<anonymous> (C:\Users\newca\Desktop\projects\nestjs\nestjs-todo\node_modules\class-validator\bundles\index.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\newca\Desktop\projects\nestjs\nestjs-todo\dist\tasks\dto\create-task.dto.js:12:27)

**Comment by crempouji** [comment]
same here :(

**Comment by mariamtsartsidze** [comment]
same :(

**Comment by vlapo** [comment]
Are you sure it is `0.12.0-rc.0`. This looks more like problem in new experimental `0.12.0-refactor.2` version published lately.

**Comment by crempouji** [comment]
The 0.12.0-rc.0 is working fine for me, but the 0.12.0-refactor.1 and 0.12.0-refactor.2 the problem starts.

What you can do is downgrade the version back to 0.12.0-rc.0.

You can see the list of versions using ```yarn info class-validator``` and then just ```yarn upgrade class-valitador@<version>```

**Comment by gpa** [comment]
Also affected

**Comment by vlapo** [comment]
`refactor.` versions are unstable. Please use `0.11` or `0.12.0-rc.0` until stable `0.12` released :)

**Comment by vlapo** [comment]
What environment do you use? Browser or Nodejs? What frameworks?

**Comment by mariamtsartsidze** [comment]
I use nestjs

**Comment by mariamtsartsidze** [comment]
> What environment do you use? Browser or Nodejs? What frameworks?

downgrading to 0.11.1 worked fine for me

**Comment by vlapo** [comment]
Changed `latest` and `stable` npm tag to `v0.11.1`. Sorry for the troubles.
