### ISSUE TITLE
isUrl not working

### ISSUE THREAD

**Issue by kaykhancheckpoint** [typestack/class-validator#619]
### Description

isUrl not working and returns the following error.

>   TypeError: Cannot read property '0' of undefined
> 
>       at Validator.validateValueByMetadata (src/validation/Validator.ts:208:64)
>       at src/validation/ValidationExecutor.ts:236:44

### Reproduction
```
import { ValidationSchema } from "class-validator";

export let InputValidationSchema: ValidationSchema  = {
    name: "inputSchema",
    properties: {
        entity_type: [{
            type: "isString"
        }],
        entity_id: [{
            type: "isString"
        }],
        url: [{
            type: "isUrl"
        }],
    }
};

```

### Environment

- [x] nodejs: v12.16.3

**class-validator version:**  "class-validator": "0.11.1"

**Comment by kaykhancheckpoint** [comment]
Fixed by adding empty constraint

```
  url: [{
            type: "isUrl",
            constraints: []
        }],
```
