### ISSUE TITLE
Using @ValidateNested with an array that contains a null element will result in a crash.

### ISSUE THREAD

**Issue by p722** [typestack/class-validator#632]
### Description

When using the `@ValidateNested({ each: true })` annotation and passing an array with a null element (`[null]`) when calling the api the following error will be generated:
`error: ERROR_RESPONSE: {"URL":"/api/apiEndpoint","TIMESTAMP":"2020-06-10T14:01:00.367Z","REQUEST_ID":"8deba9b6-317d-442d-a2fc-3a2c3372c1c8","STATUS_CODE":null,"MESSAGE":"Cannot read property 'constructor' of null"}
error: Internal server error
error: TypeError: Cannot read property 'constructor' of null
at ValidationExecutor.execute (/usr/src/app/src/validation/ValidationExecutor.ts:55:90)
at /usr/src/app/src/validation/ValidationExecutor.ts:353:26
at Array.forEach (<anonymous>)
at /usr/src/app/src/validation/ValidationExecutor.ts:349:32
at Array.forEach (<anonymous>)
at ValidationExecutor.nestedValidations (/usr/src/app/src/validation/ValidationExecutor.ts:336:19)
at ValidationExecutor.performValidations (/usr/src/app/src/validation/ValidationExecutor.ts:187:14)
at /usr/src/app/src/validation/ValidationExecutor.ts:92:22
at Array.forEach (<anonymous>)
at ValidationExecutor.execute (/usr/src/app/src/validation/ValidationExecutor.ts:81:39)`

I would like to know is there is a workaround for this as a null element in the array is not permitted but nothing that I tried worked as it would always result in a crash.

### Reproduction

Using the classes below and calling the endpoint with `{measurements: [null]}` will generate the error.

`export class Class1 {
  
  @Type(() => MeasurementDto)
  @IsArray()
  @ValidateNested({ each: true })
  @ArrayNotEmpty()
  @ApiProperty({
    type: MeasurementDto,
    isArray: true
  })
  public measurements: MeasurementDto[];
}`

`export class MeasurementDto {
  @IsEnum(MeasurementTypeEnum)
  @ApiProperty({
    enum: MeasurementTypeEnum
  })
  public measurementType: MeasurementTypeEnum;

  @IsString()
  @ApiProperty()
  public measurementUnit: string;

  @IsString()
  @ApiProperty()
  public productIncluded: string;

  @IsNumber()
  @Transform(decimalRoundingTransformer)
  @ApiProperty()
  public quantity: number;
}`

### Environment

- [x] nodejs: 10.10.0
- [] browser: 
- [x] framework/library: nestjs 7.0.11 
**class-validator version:** <code>0.11.1</code>

**Comment by c0mradeuc** [comment]
Hello, what if you use "@IsDefined({ each: true})" ?
