### ISSUE TITLE
TypeError: Cannot read property 'constructor' of undefined, when trying to validate a body property with DTO

### ISSUE THREAD

**Issue by bluerid** [typestack/class-validator#643]
### Description
When trying to use the `validate` method to validate with DTO in a custom validator, I'm getting this error... 
```
[Nest] 20094   - 06/20/2020, 10:54:52   [ExceptionsHandler] Cannot read property 'constructor' of undefined +13666ms
TypeError: Cannot read property 'constructor' of undefined
    at ValidationExecutor.execute (/var/nodedev-2/channel4/node_modules/class-validator/bundles/index.umd.js:339:92)
    at Validator.coreValidate (/var/nodedev-2/channel4/node_modules/class-validator/bundles/index.umd.js:642:22)
    at Validator.validate (/var/nodedev-2/channel4/node_modules/class-validator/bundles/index.umd.js:651:25)
    at Object.validate (/var/nodedev-2/channel4/node_modules/class-validator/bundles/index.umd.js:3222:48)
    at JsonValidatePipe.transform (/var/nodedev-2/channel4/dist/pipes/json-validate.pipe.js:25:52)
    at /var/nodedev-2/channel4/node_modules/@nestjs/core/pipes/pipes-consumer.js:15:33
```

```
import { ArgumentMetadata, Injectable, PipeTransform, BadRequestException } from '@nestjs/common';
import { validate } from 'class-validator';
import { plainToClass } from 'class-transformer';

const parseJsonAsync = (jsonString) => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(JSON.parse(jsonString))
    })
  })
}

@Injectable()
export class JsonValidatePipe implements PipeTransform<any> {
  async transform(value: any, { metatype, type, data }: ArgumentMetadata) {
    console.log(">>", metatype)
    const object = plainToClass(metatype, value);
    const errors = await validate(object);
    /* if (errors.length > 0) {
      throw new BadRequestException('Validation failed');
    } */
    return parseJsonAsync(value);
  }
}
```
The error is from this line. `const errors = await validate(object);`
```
import { IsOptional, IsString, IsNotEmpty } from "class-validator"; 

export class BrandingDTO {
    @IsNotEmpty() @IsString() @ApiProperty() readonly name: string;
    @IsNotEmpty() @IsString() @ApiProperty() readonly primary_color: string;

    @IsNotEmpty() @IsString() @ApiProperty() readonly menu_color: string;
    @IsNotEmpty() @IsString() @ApiProperty() readonly background_color: string;

    @IsOptional() @IsString() @ApiProperty() readonly section_color: string;
    @IsOptional() @IsString() @ApiProperty() readonly button_border_radius: string;
    @IsOptional() @IsString() @ApiProperty() readonly button_color: string;
}

```
```
@Post('/:campaign_id')
  @UseInterceptors(FileFieldsInterceptor([
    { name: 'logo', maxCount: 1 },
    { name: 'background', maxCount: 1 },
  ], multerOptions))
  @RBAcPermissions('branding_management@create')
  @UseGuards(AuthGuard('jwt'), RBAcGuard)
  @ApiResponse({
    status: 201,
    description: 'The record has been successfully created.',
  })
  async create(
    @AuthUser() user: UserEntity,
    @Body('jsondata', JsonValidatePipe) createBranding: BrandingDTO,
    @Param('campaign_id', ParseIntPipe) campaign_id: bigint,
    @UploadedFiles() images
  ) {
    console.log(createBranding);
    return true;
  }
```

### Tech Stack

- NodeJS 12 LTS
- MySQL 8.0.02
- NestJS, class-validator, class-transformer

**class-validator version:** <code>0.12.2</code>

**Comment by bluerid** [comment]
For anyone who is looking for a solution for this problem..

You need to make sure that the request object you are passing as `value` in `const object = plainToClass(metatype, value);` needs to a valid object for given `metatype`. In my case I was just passing the string escaped `jsondata` instead of a valid json object as value! That's why it was failing. So I converted it to a valid json object just before creating the object for given DTO. 
```
const jsonData = await parseJsonAsync(value);
const object = plainToClass(metatype, jsonData);
const errors = await validate(object, this._options);
```
That resolved the issue for me.
