### ISSUE TITLE
fix: Validation in generic class: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by Shassk** [typestack/class-validator#841]
When I try to validate object in generic class I get this error. 
Full message:

```
(node:6048) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of undefined
    at ValidationExecutor.execute (E:\Work\node\typeorm_1\node_modules\src\validation\ValidationExecutor.ts:54:90)
    at Validator.coreValidate (E:\Work\node\typeorm_1\node_modules\src\validation\Validator.ts:30:18)
    at Validator.<anonymous> (E:\Work\node\typeorm_1\node_modules\src\validation\Validator.ts:72:35)
    at step (E:\Work\node\typeorm_1\node_modules\tslib\tslib.js:141:27)

    at Object.next (E:\Work\node\typeorm_1\node_modules\tslib\tslib.js:122:57)
    at E:\Work\node\typeorm_1\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (E:\Work\node\typeorm_1\node_modules\tslib\tslib.js:111:16)
    at Validator.validateOrReject (E:\Work\node\typeorm_1\node_modules\class-validator\bundles\index.umd.js:657:28)
    at Object.validateOrReject (E:\Work\node\typeorm_1\node_modules\src\index.ts:71:44)

```
Sample of class:

```
export class GenericController<T>
{
	constructor(Type: { new(): T}, private app: Application, connection: Connection, path: string)
	{
		this.routes(Type, connection, path);
	}
	
	public routes(Type: { new(): T }, connection: Connection, path: string): void
	{
		// . . .
		this.app.post(path + "/add", async function (req, res) {
			console.log("post at:", path+"/add");
			const changed_item = plainToClass(Type, req.body, { excludeExtraneousValues: true });
			validate(changed_item).then(errors => {
				console.log("Error:", errors);
			});
		});
	}
}
```

Usage in index.ts:

```
import { createConnection } from "typeorm";
import express = require("express");
import { GenericController } from "./GenericController";
import { ItemsTypeOne } from "./ItemsTypeOne";

const app: express.Application = express();
createConnection().then(async connection =>
{
	new GenericProductsController(ItemsTypeOne, app, connection, "/items/type_one");
}).catch(error => console.log(error));
app.listen(3000);
```

Entity:

```
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";
import { Expose } from "class-transformer";
import { IsOptional, IsNumber, IsString } from "class-validator";

@Entity("type_one", { schema: "test_db" })
export class ItemsTypeOne {
	@PrimaryGeneratedColumn({ type: "int", name: "id" })
	@Expose()
	@IsOptional() @IsNumber()
	id: number;

	@Column("varchar", { name: "name", nullable: true, length: 255 })
	@Expose()
	@IsOptional() @IsString()
	name: string | null;
}
```

POST request has only simple { "name": "name1" } body.

**Comment by Shassk** [comment]
My bad, I'm a noob and forgot to add this:
...
import bodyParser = require("body-parser");
// . . .
app.use(bodyParser.json());
...

Welp.
