### ISSUE TITLE
fix: google-libphonenumber throws AssertionError while under test

### ISSUE THREAD

**Issue by oliversalzburg** [typestack/class-validator#873]
### Description
While my application is under test, it will throw an otherwise unclear `AssertionError: Assertion failed`. This does not happen during production runs, as far as I'm aware.

**Minimal code-snippet showcasing the problem**
This is not trivial, but I can work on a reproduction, if no workaround is obvious.

### Expected behavior
Either no exception should be surfaced or the root cause should be made clear.

### Actual behavior
I assume the behavior is related to using [Jest mocks](https://jestjs.io/docs/en/es6-class-mocks).

In my tests, I need to mock a module I control. I do so via `jest.mock("@scope/my-module")`. Doing so causes the AssertionError to be thrown ultimately. I need to mock the module, as it exports a class I need to mock during test.

The mocked module also contains classes that utilize `class-validator`, which in turn imports `google-libphonnumber`, which then asserts something and throws.

It is not clear why this approach is problematic, I couldn't make sense of the minified code to see what the assertion actually checks.
```
  ● Test suite failed to run

    AssertionError: Assertion failed

      at new goog.asserts.AssertionError (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:83:1084)
      at Object.goog.asserts.doAssertFailure_ (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:84:257)
      at Object.goog.asserts.assert [as assert] (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:85:83)
      at i18n.phonenumbers.PhoneMetadata.goog.proto2.Message.checkFieldType_ (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:337:411)
      at i18n.phonenumbers.PhoneMetadata.goog.proto2.Message.set$Value (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:336:246)
      at i18n.phonenumbers.PhoneMetadata.setInternationalPrefix (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:403:204)
      at Object.<anonymous> (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:1171:143)
      at Object.<anonymous> (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:1204:4)
      at Object.1 (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:1204:17)
      at o (.yarn/cache/google-libphonenumber-npm-3.2.15-f2a51666f5-55c0674487.zip/node_modules/google-libphonenumber/dist/libphonenumber.js:1:728)
```

Relates to #497

**Comment by NoNameProvided** [comment]
Do you use the latest class-transformer?

**Comment by oliversalzburg** [comment]
I'm sorry the stack trace is incomplete, I'm fairly certain I traced it back to the class-validator import while inspecting the stack during debugging though.

I'm using class-validator 0.12.2. I didn't realize there was a more recent version available. I will check if I can reproduce with 0.13.1.

**Comment by oliversalzburg** [comment]
You're right, of course. I'm seeing the same issue after upgrading, because there are other modules using google-libphonenumber.

Definitely not your issue though. Sorry 😄
